server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: music-recommendation-app
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:musicdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

# Spotify API Configuration
spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID:your_spotify_client_id}
    secret: ${SPOTIFY_CLIENT_SECRET:your_spotify_client_secret}
    redirect-uri: http://localhost:8080/callback
  scopes:
    - user-read-private
    - user-read-email
    - user-top-read
    - user-read-recently-played
    - playlist-read-private
    - playlist-modify-public
    - playlist-modify-private
    - user-library-read
    - user-library-modify

# Application Configuration
app:
  recommendation:
    # ML Model Configuration
    models:
      collaborative-filtering:
        enabled: true
        similarity-threshold: 0.7
        max-recommendations: 50
      
      content-based:
        enabled: true
        feature-weight: 0.6
        max-recommendations: 30
      
      hybrid:
        enabled: true
        collaborative-weight: 0.4
        content-weight: 0.6
    
    # Debiasing Configuration
    debiasing:
      popularity-normalization:
        enabled: true
        weight: 0.3
      
      diversity-injection:
        enabled: true
        target-diversity-ratio: 0.4
        min-novelty-score: 0.6
      
      fairness-constraints:
        enabled: true
        artist-balance-threshold: 0.1
    
    # Exploration Configuration
    exploration:
      epsilon-greedy:
        enabled: true
        epsilon: 0.2
      
      thompson-sampling:
        enabled: true
        alpha: 1.0
        beta: 1.0
    
    # Context Configuration
    context:
      mood-weights:
        happy: 1.2
        sad: 0.8
        energetic: 1.1
        calm: 0.9
        focused: 1.0
        party: 1.3
        romantic: 1.1
      
      activity-weights:
        working: 0.9
        exercising: 1.2
        studying: 0.8
        relaxing: 1.0
        commuting: 1.1
        socializing: 1.2

# Logging Configuration
logging:
  level:
    com.musicrecommendation: DEBUG
    org.springframework.security: INFO
    se.michaelthelin.spotify: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 